/**
 * SQLite → PostgreSQL Data Migration Script
 *
 * Run this BEFORE switching DATABASE_URL to PostgreSQL:
 *   npx tsx scripts/export-sqlite-data.ts > scripts/seed-data.sql
 *
 * Then run the generated SQL against your PostgreSQL database:
 *   psql $POSTGRES_URL -f scripts/seed-data.sql
 */

import { createClient } from "@libsql/client";
import path from "path";
import fs from "fs";

const dbPath = path.resolve(process.cwd(), "prisma/dev.db");

if (!fs.existsSync(dbPath)) {
  console.error(`SQLite database not found at: ${dbPath}`);
  process.exit(1);
}

const client = createClient({ url: `file:${dbPath}` });

function esc(val: string | null | undefined): string {
  if (val === null || val === undefined) return "NULL";
  return `'${String(val).replace(/'/g, "''")}'`;
}

function num(val: number | null | undefined): string {
  if (val === null || val === undefined) return "0";
  return String(val);
}

function bool(val: number | boolean | null | undefined): string {
  return val ? "true" : "false";
}

function dt(val: string | null | undefined): string {
  if (!val) return "NULL";
  return `'${val}'`;
}

async function main() {
  const lines: string[] = [];
  lines.push("-- Auto-generated by export-sqlite-data.ts");
  lines.push("-- Run: psql $DATABASE_URL -f scripts/seed-data.sql");
  lines.push("");
  lines.push("SET session_replication_role = replica; -- disable FK checks");
  lines.push("");

  // Branch
  const branches = await client.execute("SELECT * FROM Branch ORDER BY id");
  if (branches.rows.length > 0) {
    lines.push("-- Branches");
    for (const r of branches.rows) {
      lines.push(
        `INSERT INTO "Branch" (id, name, "branchNum", "createdAt") VALUES (${num(r.id as number)}, ${esc(r.name as string)}, ${esc(r.branchNum as string)}, ${dt(r.createdAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // User
  const users = await client.execute("SELECT * FROM User ORDER BY id");
  if (users.rows.length > 0) {
    lines.push("-- Users");
    for (const r of users.rows) {
      lines.push(
        `INSERT INTO "User" (id, username, password, role, "branchId", "createdAt") VALUES (${num(r.id as number)}, ${esc(r.username as string)}, ${esc(r.password as string)}, ${esc(r.role as string)}, ${r.branchId ? num(r.branchId as number) : "NULL"}, ${dt(r.createdAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // Employee
  const employees = await client.execute("SELECT * FROM Employee ORDER BY id");
  if (employees.rows.length > 0) {
    lines.push("-- Employees");
    for (const r of employees.rows) {
      lines.push(
        `INSERT INTO "Employee" (id, "branchId", name, "isActive", "createdAt") VALUES (${num(r.id as number)}, ${num(r.branchId as number)}, ${esc(r.name as string)}, ${bool(r.isActive as number)}, ${dt(r.createdAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // DailyDrawer
  const drawers = await client.execute("SELECT * FROM DailyDrawer ORDER BY id");
  if (drawers.rows.length > 0) {
    lines.push("-- DailyDrawers");
    for (const r of drawers.rows) {
      lines.push(
        `INSERT INTO "DailyDrawer" (id, "branchId", date, "totalSales", "balanceValue", "yesterdayBalance", "earnestReceived", "staffDeposits", "customerDepositsIn", "adminWithdrawals", "previousEarnest", "boxesBags", "cashPurchases", "storeExpenses", "customerDepositsOut", returns, "salariesAdvances", "actualBalance", "bookBalance", notes, "fieldNotes", "customFields", "isLocked", "createdAt", "updatedAt") VALUES (${num(r.id as number)}, ${num(r.branchId as number)}, ${dt(r.date as string)}, ${num(r.totalSales as number)}, ${num(r.balanceValue as number)}, ${num(r.yesterdayBalance as number)}, ${num(r.earnestReceived as number)}, ${num(r.staffDeposits as number)}, ${num(r.customerDepositsIn as number)}, ${num(r.adminWithdrawals as number)}, ${num(r.previousEarnest as number)}, ${num(r.boxesBags as number)}, ${num(r.cashPurchases as number)}, ${num(r.storeExpenses as number)}, ${num(r.customerDepositsOut as number)}, ${num(r.returns as number)}, ${num(r.salariesAdvances as number)}, ${num(r.actualBalance as number)}, ${num(r.bookBalance as number)}, ${esc(r.notes as string)}, ${esc(r.fieldNotes as string)}, ${esc(r.customFields as string)}, ${bool(r.isLocked as number)}, ${dt(r.createdAt as string)}, ${dt(r.updatedAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // SoldItem
  const soldItems = await client.execute("SELECT * FROM SoldItem ORDER BY id");
  if (soldItems.rows.length > 0) {
    lines.push("-- SoldItems");
    for (const r of soldItems.rows) {
      lines.push(
        `INSERT INTO "SoldItem" (id, "drawerId", category, quantity) VALUES (${num(r.id as number)}, ${num(r.drawerId as number)}, ${esc(r.category as string)}, ${num(r.quantity as number)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // BankTransfer
  const banks = await client.execute("SELECT * FROM BankTransfer ORDER BY id");
  if (banks.rows.length > 0) {
    lines.push("-- BankTransfers");
    for (const r of banks.rows) {
      lines.push(
        `INSERT INTO "BankTransfer" (id, "drawerId", "bankName", amount, beneficiary, notes) VALUES (${num(r.id as number)}, ${num(r.drawerId as number)}, ${esc(r.bankName as string)}, ${num(r.amount as number)}, ${esc(r.beneficiary as string)}, ${esc(r.notes as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // Invoice
  const invoices = await client.execute("SELECT * FROM Invoice ORDER BY id");
  if (invoices.rows.length > 0) {
    lines.push("-- Invoices");
    for (const r of invoices.rows) {
      lines.push(
        `INSERT INTO "Invoice" (id, "drawerId", type, "invoiceNum", price, "employeeName", "employeeId", barcodes, "createdAt") VALUES (${num(r.id as number)}, ${num(r.drawerId as number)}, ${esc(r.type as string)}, ${esc(r.invoiceNum as string)}, ${num(r.price as number)}, ${esc(r.employeeName as string)}, ${r.employeeId ? num(r.employeeId as number) : "NULL"}, ${esc(r.barcodes as string)}, ${dt(r.createdAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // AuditLog
  const logs = await client.execute("SELECT * FROM AuditLog ORDER BY id");
  if (logs.rows.length > 0) {
    lines.push("-- AuditLogs");
    for (const r of logs.rows) {
      lines.push(
        `INSERT INTO "AuditLog" (id, "userId", username, action, details, "createdAt") VALUES (${num(r.id as number)}, ${num(r.userId as number)}, ${esc(r.username as string)}, ${esc(r.action as string)}, ${esc(r.details as string)}, ${dt(r.createdAt as string)}) ON CONFLICT (id) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // AppSetting
  const settings = await client.execute("SELECT * FROM AppSetting");
  if (settings.rows.length > 0) {
    lines.push("-- AppSettings");
    for (const r of settings.rows) {
      lines.push(
        `INSERT INTO "AppSetting" (key, value) VALUES (${esc(r.key as string)}, ${esc(r.value as string)}) ON CONFLICT (key) DO NOTHING;`
      );
    }
    lines.push("");
  }

  // Fix sequences so next INSERT gets correct IDs
  lines.push("-- Fix auto-increment sequences");
  for (const table of ["Branch", "User", "Employee", "DailyDrawer", "SoldItem", "BankTransfer", "Invoice", "AuditLog"]) {
    lines.push(`SELECT setval(pg_get_serial_sequence('"${table}"', 'id'), COALESCE((SELECT MAX(id) FROM "${table}"), 1));`);
  }
  lines.push("");
  lines.push("SET session_replication_role = DEFAULT; -- re-enable FK checks");

  console.log(lines.join("\n"));
  await client.close();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
